name: Publish Python 🐍 distribution 📦 to PyPI

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch
    tags:
      - 'v*'  # Trigger on tags that start with 'v'

jobs:
  publish:
    name: Build distribution 📦 and publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
